name: aem-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - pip:
    - pymatsolver==0.1.2
    - discretize==0.3.8
    - SimPEG==0.10.4
