name: aem-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pip:
    - geoana==0.0.5
    - pymatsolver==0.1.2
    - discretize==0.4.7
    - SimPEG==0.11.5
